spring.application.name=booking_gateway
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}